-- Capital-goods list corrected: parts, materials and consumables of the previous Ekotrace list
-- are purchased goods (3.1), not capital goods (3.2). Same rules as src/import/capitalList.ts.
SELECT set_config('app.platform', 'on', true);
UPDATE item i SET attrs = i.attrs || jsonb_build_object('capital', false, 'capitalNote', v.note)
  FROM (VALUES
  ('336310', 'Spare parts and components: purchased goods, not capital goods'),
  ('336320', 'Spare parts and components: purchased goods, not capital goods'),
  ('336330', 'Spare parts and components: purchased goods, not capital goods'),
  ('336340', 'Spare parts and components: purchased goods, not capital goods'),
  ('336350', 'Spare parts and components: purchased goods, not capital goods'),
  ('336360', 'Spare parts and components: purchased goods, not capital goods'),
  ('336370', 'Spare parts and components: purchased goods, not capital goods'),
  ('336390', 'Spare parts and components: purchased goods, not capital goods'),
  ('336412', 'Spare parts and components: purchased goods, not capital goods'),
  ('336413', 'Spare parts and components: purchased goods, not capital goods'),
  ('336415', 'Spare parts and components: purchased goods, not capital goods'),
  ('336419', 'Spare parts and components: purchased goods, not capital goods'),
  ('325411', 'Used up in operations: purchased goods, not capital goods'),
  ('325412', 'Used up in operations: purchased goods, not capital goods'),
  ('325413', 'Used up in operations: purchased goods, not capital goods'),
  ('325414', 'Used up in operations: purchased goods, not capital goods'),
  ('339113', 'Used up in operations: purchased goods, not capital goods'),
  ('339116', 'Used up in operations: purchased goods, not capital goods'),
  ('331110', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331210', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331221', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331313', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331318', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331410', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331420', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331491', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331492', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331511', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331512', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331513', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331523', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331524', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('331529', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('332111', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('332112', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('332114', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('332117', 'Spare parts and components: purchased goods, not capital goods'),
  ('332721', 'Spare parts and components: purchased goods, not capital goods'),
  ('332911', 'Spare parts and components: purchased goods, not capital goods'),
  ('332912', 'Spare parts and components: purchased goods, not capital goods'),
  ('332919', 'Spare parts and components: purchased goods, not capital goods'),
  ('332991', 'Spare parts and components: purchased goods, not capital goods'),
  ('332996', 'Spare parts and components: purchased goods, not capital goods'),
  ('332999', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('332994', 'Used up in operations: purchased goods, not capital goods'),
  ('335921', 'Material or semi-finished product: purchased goods, not capital goods'),
  ('333515', 'Used up in operations: purchased goods, not capital goods'),
  ('333612', 'Spare parts and components: purchased goods, not capital goods'),
  ('333613', 'Spare parts and components: purchased goods, not capital goods'),
  ('333995', 'Spare parts and components: purchased goods, not capital goods'),
  ('333996', 'Spare parts and components: purchased goods, not capital goods')) AS v(naics, note)
 WHERE i.code LIKE 'old:%' AND i.attrs->>'oldType' ILIKE '%capital%' AND i.attrs->>'naics' = v.naics;
UPDATE item SET attrs = attrs || jsonb_build_object('capital', false, 'capitalNote', 'Low-value accessory, normally expensed: purchased goods')
 WHERE code LIKE 'old:%' AND attrs->>'oldType' ILIKE '%capital%' AND name ~* 'keyboard|mouse';
